version: '3.8'

services:
  app:
    build: .
    container_name: my_python_app
    command: ["python", "-m", "src.main", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=my_database
      - DATABASE_USER=my_user
      - DATABASE_PASSWORD=my_password

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
